image: docker:18.09.7

services:
  - docker:18.09.7-dind

stages:
  - Build Image
  - Test Dev Image
  - Deploy Dev Build
  - Deploy BETA Build

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy:dev
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

docker build:
  stage: Build Image
  script:  
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CI_REGISTRY/tygercaddy/tygercaddy:dev -t tygercaddy/tygercaddy:dev .
  - docker build -t $CI_REGISTRY/tygercaddy/tygercaddy:dev -t tygercaddy/tygercaddy:beta .
  - docker push $CI_REGISTRY/tygercaddy/tygercaddy:dev
  

test:
  stage: Test Dev Image
  before_script:
    - docker info
    - BRANCH_LOWER=$(echo "$CI_COMMIT_REF_NAME" | awk '{print tolower($0)}')
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker stop tygercaddytest
    - docker rm tygercaddytest
    - docker rmi $CONTAINER_TEST_IMAGE
    - docker run -d -p 81:80 -p 8443:443 -p 9001:9001 --name tygercaddytest $CONTAINER_TEST_IMAGE

  script:
    - docker exec tygercaddytest /bin/bash /checkresponse.sh
  
deploy dev build:
  stage: Deploy Dev Build
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
    - docker push tygercaddy/tygercaddy:dev

deploy BETA build:
  stage: Deploy Dev Build
  script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD $DOCKERHUB_REGISTRY
    - docker push tygercaddy/tygercaddy:beta