image: jdrouet/docker-with-buildx:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_DEV_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy:dev

services:
  - docker:dind

build:
  stage: build
  rules: 
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
  script:
    - docker context create tygercaddy
    - docker buildx create --name multiarch-builder --driver docker-container --use tygercaddy
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx build --platform linux/amd64 -t $CONTAINER_DEV_IMAGE . --push