variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CI_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy
  CONTAINER_DEV_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy:dev
  PLATFORM: linux/amd64,linux/arm64,linux/arm/v7 #,linux/arm/v6

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker buildx create --driver docker-container --use
  - docker buildx inspect --bootstrap

build-release:
  image: jonoh/docker-buildx-qemu
  stage: build
  services:
    - docker:19.03.0-dind
  script:
    - update-binfmts --enable
    - docker buildx build -t "$CI_IMAGE" --cache-from $CI_IMAGE --platform "$PLATFORM" --push $CI_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 .
  only:
    - master

build-test:
  image: jonoh/docker-buildx-qemu
  stage: build
  services:
    - docker:19.03.0-dind
  script:
    - update-binfmts --enable
    - docker buildx build --push -t "$CI_IMAGE:$CI_COMMIT_REF_SLUG-test" 
      --platform "linux/amd64"
      --cache-from $CI_IMAGE 
      --build-arg BUILDKIT_INLINE_CACHE=1 .
  except:
    - master
    - dev

build-dev:
  image: jonoh/docker-buildx-qemu
  stage: build
  services:
    - docker:19.03.0-dind
  script:
    - update-binfmts --enable
    - docker buildx build --push -t "$CI_IMAGE:$CI_COMMIT_REF_SLUG" 
      --cache-from $CI_IMAGE
      --platform "linux/amd64" 
      --build-arg BUILDKIT_INLINE_CACHE=1 .
  except:
    - master
    - test
