variables:
  CI_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy
  CONTAINER_DEV_IMAGE: $CI_REGISTRY/tygercaddy/tygercaddy:dev
  PLATFORM: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use

build-master:
  image: jdrouet/docker-with-buildx:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker buildx build --push -t "$CI_IMAGE"
      --platform "$PLATFORM" --cache-from "$CI_IMAGE"
      --build-arg BUILDKIT_INLINE_CACHE=1 .
  only:
    - master

build-feature:
  image: jdrouet/docker-with-buildx:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker buildx build --push -t "$CI_IMAGE:$CI_COMMIT_REF_SLUG" 
      --platform "$PLATFORM" --cache-from "$CI_IMAGE:$CI_COMMIT_REF_SLUG"
      --build-arg BUILDKIT_INLINE_CACHE=1 .
  except:
    - master
