plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
  - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/gitlab"
  - "semantic-release-gitlab-registry"
branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "test"
    prerelease: "test"
release: 
  - verifyConditions: "semantic-release-gitlab-registry"
  - publish:
    - path: "semantic-release-gitlab-registry"
    - name: "tygercaddy/tygercaddy"