<template>
  <div>
    <v-layout row wrap>
      <v-flex xs12 sm12 pa-3>
        <v-card flat class="blue-grey lighten-5">
          <v-toolbar color="orange" dark flat>
            <v-toolbar-title>Backup</v-toolbar-title>
            <v-spacer></v-spacer>

            <v-icon large color="white">mdi-domain</v-icon>
          </v-toolbar>
          <v-card-title primary-title>
            <v-row class="mb-6" no-gutters>
              <v-col class="d-none d-lg-block">
                <h2 class="blue-grey--text darken-4">Backup</h2>
              </v-col>

              <v-col class="text-right">
                <v-btn rounded color="orange" dark @click.stop="">
                  <v-icon dark>mdi-plus</v-icon>
                  <div class="d-none d-lg-block">Backup</div>
                </v-btn>
              </v-col>
            </v-row>
          </v-card-title>
        </v-card>
      </v-flex>
      <v-flex xs12 sm12 pa-3>
        <v-card flat class="blue-grey lighten-5">
          <v-toolbar color="orange" dark flat>
            <v-toolbar-title>Restore</v-toolbar-title>
            <v-spacer></v-spacer>

            <v-icon large color="white">mdi-domain</v-icon>
          </v-toolbar>
          <v-card-title primary-title>
            <v-row class="mb-6" no-gutters>
              <v-col class="d-none d-lg-block">
                <h2 class="blue-grey--text darken-4">Restore</h2>
              </v-col>
            </v-row>
          </v-card-title>
          <v-container>
            <h4>Restore from TygerCaddy:</h4>
            <v-row>
              <v-col>
                <v-file-input
                chips
                clearable
                persistent-hint
                hint="Only upload a JSON file generated by TygerCaddy. Using a Tyger2 JSON file, or a custom file, could break your install."
                  accept="application/json"
                  label="TygerCaddy JSON File"
                  color="orange"
                  @change="selectTygerCaddy"
                ></v-file-input>
              </v-col>

              <v-col>
                <v-btn rounded color="orange" dark @click.stop="TygerCaddyRestore()">
                  <v-icon dark>mdi-plus</v-icon>
                  <div class="d-none d-lg-block">Restore</div>
                </v-btn>
              </v-col>
            </v-row>

            <h4>Restore from Tyger2:</h4>
            <v-row>
              <v-col>
                <v-file-input
                chips
                clearable
                persistent-hint
                hint="Only upload a JSON file generated by Tyger2. Using a TygerCaddy JSON file, or a custom file, could break your install."
                  accept="application/json"
                  label="Tyger2 JSON File"
                  color="orange"
                   @change="selectTyger2"
                ></v-file-input>
              </v-col>

              <v-col>
                <v-btn rounded color="orange" dark @click.stop="Tyger2Restore()">
                  <v-icon dark>mdi-plus</v-icon>
                  <div class="d-none d-lg-block">Restore</div>
                </v-btn>
              </v-col>
            </v-row>
          </v-container>
        </v-card>
      </v-flex>
    </v-layout>
  </div>
</template>
<script>
export default {
  data() {
    return {
      tyger2File: undefined,
      tygercaddyFile: undefined,
    };
  },
  components: {},
  methods: {
    selectTyger2(file){
      this.tyger2File = file
    },
    selectTygerCaddy(file){
      this.tygercaddyFile = file
    },

    TygerCaddyRestore(){
      if(!this.tygercaddyFile){
        let message={
          snack:"Error! You can not restore without first uploading the backup file. ",
          color:"error"
        }
        this.$store.dispatch('fireSnack', message)
      } else{
console.log(this.tygercaddyFile)
      let reader = new FileReader()
      reader.onload = e =>{
        let Json = JSON.parse(e.target.result);
        console.log(Json)
      };
      reader.readAsText(this.tygercaddyFile)
      }
      
    },
    Tyger2Restore(){
               if(!this.tyger2File){
        let message={
          snack:"Error! You can not restore without first uploading the backup file. ",
          color:"error"
        }
        this.$store.dispatch('fireSnack', message)
      } else{
console.log(this.tyger2File)
      let reader = new FileReader()
      reader.onload = e =>{
        let Json = JSON.parse(e.target.result);
        console.log(Json)
      };
      reader.readAsText(this.tyger2File)
      }
    }
  },
  computed: {}
};
</script>
